# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='votes',
        ),
        migrations.AddField(
            model_name='information',
            name='day',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='information',
            name='month',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='information',
            name='year',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='information',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='mood',
            field=models.IntegerField(),
        ),
    ]
