# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170506_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
